### PR TITLE
Adding linters to for rule checks

### PR DESCRIPTION
**Pull request by leehaney254**
I have added linters to make sure the code is in line with our guidelines

### CODE REVIEW

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @leehaney254, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Try-Again

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._
- [x] Please kindly add a more descriptive PR title and description using past tense as seen in the demo below:

pull_request_desc

- [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
image

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- As you'll need to create a new pull request to change your branch name. I kindly suggest that for future pull request your should have a name of a feature or action (e.g. 'feature/SetupHelloMicroverse') as your branch name

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by leehaney254** [comment]
I mistakenly merged my branch. However, I have made the requested changes on [this branch](https://github.com/leehaney254/Hello-World/pull/2). Sorry for any inconvenience, and thank you for understanding.

**Comment by leehaney254** [comment]
Thank you very much for your guidance. In future I will use better commit messages.

**Comment by topeogunleye** [comment]
> Thank you very much for your guidance. In future I will use better commit messages.



> I mistakenly merged my branch. However, I have made the requested changes on [this branch](https://github.com/leehaney254/Hello-World/pull/2). Sorry for any inconvenience, and thank you for understanding.

You can revert a merged branch.  Please kindly read this [article](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request).  If reverting creates a new PR, I suggest that you add the link of this PR to your new PR's description and a note to the reviewer

**Comment by leehaney254** [comment]
I believe [this](https://github.com/leehaney254/Hello-World/pull/2) is the reverted merge

**Comment by leehaney254** [comment]
Thank you.

**Pull request merged**
